### ISSUE TITLE
jquery.tokeninput error

### ISSUE THREAD

**Issue by BenaeSan** [hypeJunction/elgg_tokeninput#10]
Hello sir, 

I want to use your plug-in with an elgg 2.3 version, but when I add an input/tokeninput in my form, i got " Script error for "jquery.tokeninput", needed by: tokeninput/lib" message in my JavaScript console.

Is this plug-in not working with Elgg 2.3 ?

**Comment by hypeJunction** [comment]
It's working fine in Elgg 2.3. Can't tell you more without knowing how you installed the plugin, what other plugins you have. Check the console. Enable and flush the simplecache. There is a bunch of possibilities of what can go wrong. I'd start by downloading from the releases tab and reuploading, flushing the caches.

**Comment by BenaeSan** [comment]
Ok thank, So it's supposed to work on Elgg 2.3. I'll will investigate to see why that doesn't work with me. I'll give you some news after that.

**Comment by BenaeSan** [comment]
Hello, 
After some research, when i put an tokeninput field in my form, i got a 403 error with jquery.tokeninput.js. That sound weird, but I don't know why. For testing, I've made a mini plugin (start, manifest, 1 resource). In the resource :

`$title = "test token input";

$body = elgg_view("input/tokeninput");

echo elgg_view_page($title, $body);`

**Comment by BenaeSan** [comment]
My bad, sorry for the disturbance. That work for now. That a plugin version problem in my project.
