### ISSUE TITLE
not working in plugin settings page

### ISSUE THREAD

**Issue by beck24** [hypeJunction/elgg_tokeninput#3]
If a plugin setting action is registered to save non-standard inputs (that can't be set using the 'params' magic input name) - action() is called twice therefore this hook is called twice.
The first time it sets the input as an array which is correct, the second time it sets it as an empty string.

```
$elgg_tokeninput_fields = get_input('elgg_tokeninput_fields');

	if ($elgg_tokeninput_fields) {
		foreach ($elgg_tokeninput_fields as $field_name) {
			$values = explode(',', get_input($field_name, ''));
			set_input($field_name, $values);
		}
		set_input($elgg_tokeninput_fields, null);
	}
```

Somehow the set_input($elgg_tokeninput_fields, null); doesn't seem to be working

**Comment by hypeJunction** [comment]
This should read:
```set_input('elgg_tokeninput_fields', null);```
Fixed now
