### ISSUE TITLE
Problem with message plugin

### ISSUE THREAD

**Issue by jardao** [hypeJunction/elgg_tokeninput#5]
Hi. Today I have got a little problem with the message plugin and this plugin. After autocompleting the recipient of the message and sending the message, we receive the error message "We could not find the recipient in the user database". Then, I have decided to desactivate the elgg_tokeninput plugin, and the problem disappeared. I could send the message successfully.

Thanks for your atention. Regards

**Comment by propertunist** [comment]
i am also seeing this in elgg 1.11.2
